version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    command: npm run dev
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - SUPER_PASSWORD=${SUPER_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_CLIENT_ID=${EMAIL_CLIENT_ID}
      - EMAIL_CLIENT_SECRET=${EMAIL_CLIENT_SECRET}
      - EMAIL_REFRESH_TOKEN=${EMAIL_REFRESH_TOKEN}
      - EMAIL_FROM=${EMAIL_FROM}
      - OTP_EXP_TIME=${OTP_EXP_TIME}
    ports:
      - "3002:3002"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  db_data: